services:
  - type: web
    name: maxvy-whatsapp-bot
    env: docker
    region: singapore
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.0-flash
      - key: BOT_PREFIXES
        value: ".,!,/"
      - key: ACTIVATION_COMMAND
        value: maxactivate
      - key: DEACTIVATION_COMMAND
        value: maxdeactivate
      - key: LOG_LEVEL
        value: info
    autoDeploy: true
